feat: add timeline for versions

diff --git a/docs/get b/docs/get
--- a/docs/get
+++ b/docs/get
@@ -2,26 +2,36 @@
 set -Eeuo pipefail
 
 REPO_URL="https://github.com/eq-desktop/cli.git"
-REPO_NAME="cli"
+PIP_ARGS=()
 
 log() { printf "\033[1;32m[+] %s\033[0m\n" "$*"; }
 err() { printf "\033[1;31m[!] %s\033[0m\n" "$*" >&2; }
 die() { err "$*"; exit 1; }
 
 command -v git >/dev/null || die "git is required"
+command -v pip >/dev/null || die "pip is required"
+
+# --- parse arguments ---
+while [[ $# -gt 0 ]]; do
+    case "$1" in
+        --pip-args)
+            shift
+            [[ $# -gt 0 ]] || die "--pip-args requires a value"
+            PIP_ARGS+=($1)
+            ;;
+        *)
+            die "Unknown argument: $1"
+            ;;
+    esac
+    shift
+done
 
 tmp="$(mktemp -d)"
 trap 'rm -rf "$tmp"' EXIT
 
-log "Cloning repository"
-git clone --depth=1 "$REPO_URL" "$tmp/$REPO_NAME"
+log "Installing CLI (using pip)"
 
-cd "$tmp/$REPO_NAME"
-
-[ -x install.sh ] || die "install.sh not found or not executable"
-
-log "Running installer"
-./install.sh
+pip install "${PIP_ARGS[@]}" "git+${REPO_URL}"
 
 aureli install
 
